name: Build KernelSU Ginkgo
on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'Kernel Source URL'
        required: true
        default: 'https://github.com/kutemeikito/android_kernel_xiaomi_ginkgo'
      repo_branch:
        description: 'Kernel Source Branch'
        required: true
        default: 'sixteen'
      config_file:
        description: 'Config File (defconfig)'
        required: true
        default: 'vendor/ginkgo-perf_defconfig'
      image_name:
        description: 'Kernel Image Name'
        required: true
        default: 'Image.gz-dtb'
      ksu_version:
        description: 'KernelSU Version'
        required: true
        default: 'v0.9.5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc
    
    - name: Clone Source & Toolchain
      run: |
        git clone --depth=1 -b ${{ github.event.inputs.repo_branch }} ${{ github.event.inputs.repo_url }} android-kernel
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Setup KernelSU
      run: |
        cd android-kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        
    - name: Build Kernel
      run: |
        cd android-kernel
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_BUILD_USER=MarsTianZ
        export KBUILD_BUILD_HOST=GitHub-Action
        
        # Inject Config KSU
        echo "CONFIG_KSU=y" >> arch/arm64/configs/${{ github.event.inputs.config_file }}
        echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/${{ github.event.inputs.config_file }}
        
        # Build command
        make O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- ${{ github.event.inputs.config_file }}
        make -j$(nproc --all) O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Image-KernelSU-Ginkgo
        path: android-kernel/out/arch/arm64/boot/${{ github.event.inputs.image_name }}
